In [1]:
# import torch
import numpy as np

In [2]:
# x_train = torch.FloatTensor([[1, 2], [2, 3], [3, 4], [4, 4], [5, 3], [6, 2]]) # [n시간 공부, n년치 족보 가짐]
# y_train = torch.FloatTensor([[0], [0], [0], [1], [1], [1]]) # 점수 (0은 F, 1은 A+)
x_train = np.array([[1, 2], [2, 3], [3, 4], [4, 4], [5, 3], [6, 2]])
y_train = np.array([[0], [0], [0], [1], [1], [1]])

In [3]:
x_train

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 4],
       [5, 3],
       [6, 2]])

In [4]:
y_train

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [ ]:
# W = torch.randn([2, 1], requires_grad=True) # 생성되는 텐서의 기울기를 계산
# = torch.randn([1], requires_grad=True)

In [ ]:
# optimizer = torch.optim.SGD([W, b], lr=0.01) # 확률적 경사 하강법 이용해 W와 b 학습하겠다고 명시

In [5]:
from keras.models import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()
model.add(Dense(1, activation = 'sigmoid')) # model
model.compile(loss = 'binary_crossentropy', optimizer = 'sgd', metrics = ['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs = 2000, verbose = 1)

Epoch 1/2000
1/1 [==============================] - 0s 30ms/step - loss: 0.1516 - accuracy: 1.0000
Epoch 2/2000
1/1 [==============================] - 0s 16ms/step - loss: 0.1515 - accuracy: 1.0000
Epoch 3/2000
1/1 [==============================] - 0s 15ms/step - loss: 0.1515 - accuracy: 1.0000
Epoch 4/2000
1/1 [==============================] - 0s 27ms/step - loss: 0.1514 - accuracy: 1.0000
Epoch 5/2000
1/1 [==============================] - 0s 20ms/step - loss: 0.1514 - accuracy: 1.0000
Epoch 6/2000
1/1 [==============================] - 0s 29ms/step - loss: 0.1514 - accuracy: 1.0000
Epoch 7/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.1513 - accuracy: 1.0000
Epoch 8/2000
1/1 [==============================] - 0s 27ms/step - loss: 0.1513 - accuracy: 1.0000
Epoch 9/2000
1/1 [==============================] - 0s 21ms/step - loss: 0.1512 - accuracy: 1.0000
Epoch 10/2000
1/1 [==============================] - 0s 16ms/step - loss: 0.1512 - accuracy: 1.0000
Epoch 11/

In [11]:
print(model.predict(x_train))

1/1 [==============================] - 0s 45ms/step
[[0.05399106]
 [0.09645004]
 [0.16642492]
 [0.7698232 ]
 [0.99801105]
 [0.9999867 ]]
